### ISSUE TITLE
Error: Secrets cannot contain multiple lines

### ISSUE THREAD

**Issue by docbyte86** [Fizcko/Azure_DevOps_Vault_Interaction#18]
Hello,

we have secrets with multiple lines in our path. (Privat Keys, for example).
In this case the pipeline breaks with the following error:

(node:118) UnhandledPromiseRejectionWarning: Error: Error during browsing engine. Error when exporting values. Error when exporting values. Error: Secrets cannot contain multiple lines
    at /__w/_tasks/VaultReadKV_807a85d5-8ac9-4b8c-a0fc-1b233bb2bcc6/4.0.1/kv_read.js:77:35
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:118) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:118) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
##[error]Error during browsing engine. Error when exporting values. Error when exporting values. Error: Secrets cannot contain multiple lines

**Comment by Fizcko** [comment]
Hi @docbyte86 ,

You have to use the option "Replace carriage return by a token".

Then you have to replace back the token by yourself or use the second tool of this extension "Tool - Create a File".

See more details in file [overview.md](https://github.com/Fizcko/Azure_DevOps_Vault_Interaction/blob/master/overview.md) > Tool - Create a File > Use case 1

regards

**Comment by docbyte86** [comment]
@Fizcko , thanks for the fast reply. we tried the following parameters:

strCRPrefix: '(LF, \n)'
strCRPrefix: 'LF, \n'
strCRPrefix: '\n'
strCRPrefix: '(\n)'
strCRPrefix: 'LF'

suddenly with the same results. Can you give some more details about the syntax?

**Comment by Fizcko** [comment]
For this exemple you have a vault multine secret like this:
```
-----BEGIN CERTIFICATE-----
MIIDfjCCAmagAwIBAgIEGWY2EzANBgkqhkiG9w0BAQsFADBbMScwJQYDVQQDDB5SZWdlcnkgU2Vs
Zi1TaWduZWQgQ2VydGlmaWNhdGUxIzAhBgNVBAoMGlJlZ2VyeSwgaHR0cHM6Ly9yZWdlcnkuY29t
MQswCQYDVQQGEwJVQTAgFw0yMzA2MjkwMDAwMDBaGA8yMTIzMDYyOTE0MzU1MlowQDEMMAoGA1UE
-----END CERTIFICATE-----
```

Using task "Vault - Read KV secrets" with settings:
```yaml
replaceCR: true
strCRPrefix: "#{rn}#"
```

This will load this secret in variable in this format : 
```
-----BEGIN CERTIFICATE-----#{rn}#MIIDfjCCAmagAwIBAgIEGWY2EzANBgkqhkiG9w0BAQsFADBbMScwJQYDVQQDDB5SZWdlcnkgU2Vs#{rn}#Zi1TaWduZWQgQ2VydGlmaWNhdGUxIzAhBgNVBAoMGlJlZ2VyeSwgaHR0cHM6Ly9yZWdlcnkuY29t#{rn}#MQswCQYDVQQGEwJVQTAgFw0yMzA2MjkwMDAwMDBaGA8yMTIzMDYyOTE0MzU1MlowQDEMMAoGA1UE#{rn}#-----END CERTIFICATE-----
```

Then you have to replace back the token (#{rn}#) by yourself or use the second tool of this extension "Tool - Create a File".

**Comment by docbyte86** [comment]
thank you very much. it works. but it is possible to use another token like "\n" instead of "#n#". ?

**Comment by Fizcko** [comment]
Yes you can enter anything you want
